name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # chạy hàng ngày lúc 00:00
  workflow_dispatch:              # cho phép chạy thủ công

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN_NEW }}
          user: aimachinius
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_isocalendar: yes
          plugin_followup: yes
          filename: metrics.svg
          output_action: commit
          output_condition: always 
